allOf:
  - $ref: '../../base/schemas/Object.yaml'
  - type: object
    description: Товар
    properties:
      name:
        type: string
        description: Название для отображения на клиенте
        example: Мантия
