image: node:12

stages:
  - build
  - deploy
  - notify_success
  - notify_failure

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

.build:
  stage: build
  tags:
    - web
  script:
    - yarn install
    - yarn run bundle
  artifacts:
    paths:
      - build/

.deploy:
  stage: deploy
  tags:
    - web
  script:
    - echo "Uploading build"
    - |
      curl --request POST "https://api.swaggerhub.com/apis/$SWAGGERHUB_OWNER/$SWAGGERHUB_API_NAME" \
        --header "Authorization: $SWAGGERHUB_API_KEY" \
        --header "Content-Type: application/yaml" \
        --data-binary @build/swagger/online_store_api.yaml
    - echo "Build uploaded"

.notify_success:
  stage: notify_success
  tags:
    - web
  script:
    - ./gitlab_ci_slack_notification.sh -s success

.notify_failure:
  stage: notify_failure
  tags:
    - web
  script:
    - ./gitlab_ci_slack_notification.sh -s failure
  when: on_failure

build:production:
  extends: .build
  only:
    refs:
      - master
  environment: production

deploy:production:
  extends: .deploy
  only:
    refs:
      - master
  environment: production

notify_success:production:
  extends: .notify_success
  only:
    refs:
      - master
  environment: production

notify_failure:production:
  extends: .notify_failure
  only:
    refs:
      - master
  environment: production
