openapi: 3.0.0
info:
  version: 1.0.0
  title: Интернет-магазин
  description: Пример REST API интернет-магазина
servers:
  - url: 'https://online-store.com/api/v1'
security:
  - BearerAuth: []
paths:
  $ref: './_paths.yaml'
components:
  parameters:
    $ref: './_parameters.yaml'
  examples:
    $ref: './_examples.yaml'
  schemas:
    $ref: './_schemas.yaml'
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
